services:
  - type: web
    name: terms-conditions-backend
    env: docker
    rootDir: backend
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health/status
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: FRONTEND_URL
        sync: false

